### ISSUE TITLE
Ignored slide mids should be rendered differently

### ISSUE THREAD

**Issue by sevenc-nanashi** [crash5band/MikuMikuWorld#16]
It's too hard to check if the midpoint is ignored or visible.
Ignored one should be rendered differently, like changing border color.

**Comment by crash5band** [comment]
![step-outline-update](https://user-images.githubusercontent.com/44091782/190421921-bf0727ae-fb15-4dce-81c9-e39a808bf385.png)
Is this good enough or should I try a different color?

**Comment by sevenc-nanashi** [comment]
Looks good, tysm
