### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by reochandesu** [crash5band/MikuMikuWorld#2]
Hi, i just downloaded the pre-built binary and it's not working, i double clicked at the executable many times but the program won't open

**Comment by crash5band** [comment]
So when you extract the zip file and double click it doesn't start? Does it at least show an error message or anything?

**Comment by reochandesu** [comment]
> So when you extract the zip file and double click it doesn't start? Does it at least show an error message or anything?

yes, it doesn't start, and no error message was showed

**Comment by crash5band** [comment]
I'm not sure what's preventing it from starting but if you can, open the solution in visual studio, place a break point at the entry point and look if it is returning early from there.

**Comment by crash5band** [comment]
Alternatively you can try and see if this build works or shows anything. If that fails then check your windows logs.
[MikuMikuWorld_V1.2.0_gl_err_chk.zip](https://github.com/crash5band/MikuMikuWorld/files/8753852/MikuMikuWorld_V1.2.0_gl_err_chk.zip)

**Comment by reochandesu** [comment]
> Alternatively you can try and see if this build works or shows anything. If that fails then check your windows logs. [MikuMikuWorld_V1.2.0_gl_err_chk.zip](https://github.com/crash5band/MikuMikuWorld/files/8753852/MikuMikuWorld_V1.2.0_gl_err_chk.zip)

hmm it said failed to create GLFW window

**Comment by reochandesu** [comment]
> > Alternatively you can try and see if this build works or shows anything. If that fails then check your windows logs. [MikuMikuWorld_V1.2.0_gl_err_chk.zip](https://github.com/crash5band/MikuMikuWorld/files/8753852/MikuMikuWorld_V1.2.0_gl_err_chk.zip)
> 
> hmm it said failed to create GLFW window

i think it failed due to the graphic card or the opengl driver was outdated, i know how to fix it, so thank you for giving me the gl error check build. I will close this issue now
