### ISSUE TITLE
No VC Resdist listed as dependency

### ISSUE THREAD

**Issue by natsukashiixo** [crash5band/MikuMikuWorld#20]
Helped someone download and run the project. 
They ran into _"The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem"_
Listing and linking the proper redists needed would be helpful

**Comment by crash5band** [comment]
Updated readme to include requirements dfb647b7f82846fa83263491ff989c45c6383065
