### ISSUE TITLE
sus using chart speed changing doesn't export collectly

### ISSUE THREAD

**Issue by Oomisokadesu** [crash5band/MikuMikuWorld#26]
![0C092F9C-4311-4D6D-A1F5-E4C9FBC04943](https://user-images.githubusercontent.com/94232856/229682861-4b088566-92f7-4d55-8be0-043fd67ad491.jpeg)
I made this chart.
I saved it by .mmws and exported it by .sus .
.mmws chart can be inported collectly, but .sus chart can't collectly like this.
![AB3270DA-BDC4-4E90-BB2C-4E52128A40E4](https://user-images.githubusercontent.com/94232856/229683232-e5126c0e-9e5c-4b59-a294-bca91a92a33e.jpeg)
I tested this sus but timings sped up or down aren't right so I guess not .sus importing system but exporting doesn't work.
I think using BPM, tempo and speeding at same time cause bug.
(I use win.10 , MMW v2.2.0)

**Comment by crash5band** [comment]
Fixed as of 67878cf
