### ISSUE TITLE
exporting is still not collect

### ISSUE THREAD

**Issue by Oomisokadesu** [crash5band/MikuMikuWorld#30]
![IMG_5885](https://user-images.githubusercontent.com/94232856/230695069-ce53260b-e7e9-4afd-9633-97d3b5dc3daa.jpeg)
this is .mmws
![IMG_5884](https://user-images.githubusercontent.com/94232856/230695084-dfd910ae-9005-4ddf-a028-47d31b22d401.jpeg)
this is exported .sus
some bpm changes are delayed
used MMW ver.2.2.1

**Comment by crash5band** [comment]
I have updated the latest release with a fix, so please download v2.2.1 again and see if it works properly.

**Comment by Oomisokadesu** [comment]
it wasn't changed.

**Comment by crash5band** [comment]
So it is exporting correctly now?

**Comment by Oomisokadesu** [comment]
no, redownloaded MMW didn't export correctly.
it was same as 2.2.0.

**Comment by crash5band** [comment]
Can you send me the `.mmws` and `.sus`?

**Comment by Oomisokadesu** [comment]
sorry, it worked.

old mmw v2.2.1 didn't export correctly but new one v2.2.1 worked properly.
it seems i used old one again.
but i wonder what is the difference between new and old.
if old 2.2.1 is same as 2.2.0 , i suggest that new 2.2.1 should be renamed 2.2.2.

**Comment by crash5band** [comment]
Ah okay that is good. I'll close this for now but feel free to open it again if you encounter another problem.
