### ISSUE TITLE
UI too small in some environments

### ISSUE THREAD

**Issue by waki285** [crash5band/MikuMikuWorld#37]
On my PC, the UI of the MikuMikuWorld application is too small and difficult to operate. (see attached file).
![image](https://github.com/crash5band/MikuMikuWorld/assets/67305123/74a1ec97-2256-47a4-bfb4-9484b2176025)

OS: Windows 11 Pro
Display: 3840 x 2160 (60Hz)
Display magnification: 225%

**Comment by crash5band** [comment]
Fixed with 789e677. I'll publish a new release with the fix soon
