### ISSUE TITLE
Some configs aren't being saved/read

### ISSUE THREAD

**Issue by Khronophobia** [crash5band/MikuMikuWorld#40]
I've noticed some things that aren't being saved/read, occuring from v2.3 onwards:

- Audio volumes (values listed in app_config.json, but ignored)
- Division (same as above)
- Presets (Previously saved presets are read, but creating new presets aren't saved. They'll disappear once you restart MMW)

**Comment by crash5band** [comment]
Fixed with 600f06f and 7dd0cb0.
Thanks for reporting
