### ISSUE TITLE
(Advanced) Feature Request

### ISSUE THREAD

**Issue by TootieJin** [crash5band/MikuMikuWorld#43]
Few advanced features (in Chart Cyanvas server only, can be toggled or something) that I would like to add
- Expand lane count up to 36 lanes (based on [sus specifications](https://gist.github.com/kb10uy/c171c175ba913dc40a73c6ce69da9859), using all possible lanes in 1 digit from 0-9, a-z).
- (optional) Layers, to do things like applying speed change in different "layers" (example in attachment)
![image](https://github.com/crash5band/MikuMikuWorld/assets/63959434/d24c9910-52ef-4e16-b0ea-b4cb40dc92ba).
- Damage notes, catch(trace) notes, and a way to hide arrows on notes.
- Have it so that it creates a repeating pattern based on selected hold mids [like this](https://github.com/paralleltree/Ched/wiki/BuiltInPlugins-EN).

**Comment by crash5band** [comment]
Only features present in the original game will be added to keep it compatible

**Comment by crash5band** [comment]
I'll see if the last point is feasible
