### ISSUE TITLE
Editing nonexistent Hi-Speed crashes MMW

### ISSUE THREAD

**Issue by ieatlawns** [crash5band/MikuMikuWorld#46]
Version: MMW v3.0.0
Platform: Windows 10

When using the "Edit Hi-Speed" menu on a nonexistent Hi-Speed, the menu does not close and using it causes crash.
Similar behavior occurs with BPM and Time Signatures.

Hi-Speeds crash when editing the speed or deleting it.
BPMs crash only when deleting it.
Time Signatures don't crash MMW, but can create "ghost" time signatures.
![image](https://github.com/crash5band/MikuMikuWorld/assets/122433438/972fd7f1-2b58-427d-ae75-fdfff8b1fb3b)
## How to re-create:
1. Create a Hi-Speed/BPM.
2. Right-Click to open the Edit Hi-Speed/Tempo menu.
3. Undo the Hi-Speed/BPM with Ctrl+Z.
4. Change the delete the Hi-Speed/BGM.
5. MikuMikuWorld crashes.

**Comment by crash5band** [comment]
Thanks for reporting. Fixed with 062ab0a
