### ISSUE TITLE
playback speed

### ISSUE THREAD

**Issue by YumYummity** [crash5band/MikuMikuWorld#50]
Would be great if we could choose the playback speed. Playing it slower is a good way to make sure notes are synced.

**Comment by crash5band** [comment]
I'll get to it as soon as I can

**Comment by crash5band** [comment]
Implemented with 0ff8552

**Comment by YumYummity** [comment]
Thank you!

**Comment by crash5band** [comment]
Better implementation with 7977ae1 that works even when the music file's sample rate matches the device's sample rate
