### ISSUE TITLE
Feature request: Make MMW available on Mac (if possible)

### ISSUE THREAD

**Issue by hyra3434** [crash5band/MikuMikuWorld#51]
I was wondering if it would be possible to make MikuMikuWorld available for Mac users so that we could also make PJSK charts on MikuMikuWorld.

**Comment by crash5band** [comment]
No plans for a native macOS version due to usage of multiple native Windows functions. There is a running on macOS guide on the wiki but OpenGL is bugged so it runs at an uncapped framerate.

**Comment by hyra3434** [comment]
Ah ok, thank you for the response
