### ISSUE TITLE
MikuMikuWorld Does Not Work

### ISSUE THREAD

**Issue by RnalofY** [crash5band/MikuMikuWorld#53]
When I Tried Opening MikuMikuWorld It Doesn't Open For My PC It Keeps On Saying **This App Can't Run On Your PC** Please If You Can Make It So That I Can Use It Too Because I Wanna Try Charting In Sonolus PLSSSS
![Capture](https://github.com/crash5band/MikuMikuWorld/assets/155151286/923dbb73-cb26-4aeb-a687-c409a56a727d)

**Comment by crash5band** [comment]
Is this a 32-bit or ARM version of windows? Because MikuMikuWorld only works on 64-bit windows
