### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by Good4ok3** [crash5band/MikuMikuWorld#56]
![Снимок экрана (3)](https://github.com/crash5band/MikuMikuWorld/assets/164785402/1e94d021-6cb7-4014-aedd-16e1f2ffcf1b)
I wanted to download MikumikuWorld to make my own level in Sonolus, but it didn’t work out, then the application asked for dll files, I downloaded it, now I have this, help me solve this problem!!!

**Comment by crash5band** [comment]
Seems like OpenGL is failing to initialize. What's your graphics card?

**Comment by Good4ok3** [comment]
Intel HD Graphic, I also downloaded the application in the fall and then everything was fine

**Comment by crash5band** [comment]
If it worked before it should also work now. Is this a different computer? Also please specify the graphics card's full name (e.g. Intel HD Graphics 4000)

**Comment by Good4ok3** [comment]
We can say that it’s almost a different PC, in the fall the characteristics were as follows: Pentium G2020, 4 gigabytes of RAM and Intel® HD Graphics for 3rd Generation Intel® Processors. Now: Core i3 540,4 gigabytes RAM, Intel® HD Graphics for Previous Generation Intel® Processors.I found information about the graphics card only on the Internet, since Aida 64 did not have the full name

**Comment by crash5band** [comment]
That gpu is too old to run it... It only supports opengl 2.1 and MikuMikuWorld requires a gpu with opengl 3.3.

**Comment by Good4ok3** [comment]
Oh.....It's a shame(
