### ISSUE TITLE
Select bug

### ISSUE THREAD

**Issue by kaieri-4946** [crash5band/MikuMikuWorld#6]
There's a bug when using hold-click to select in the Note Timeline where the selection box and what is selected is not accurate to the hold-click movement.

Step to reproduce:
1. Click anywhere inside the Note Timeline window, let's call the position of this click (1) for easier explanation
2. Click on another window in the app (Toolbox, Controls, ...)
3. Hold-click inside the Note Timeline window (for selecting multiple notes for example). Let's call the initial position of this hold-click (2) and the position after that where the mouse is dragging is (3).

Usually, the selection box should be drawn as a rect from (2) to (3), but in this case, it's drawn from (1) to (3) instead, and notes that are selected are also based on the select box drawn from (1) to (3).

Not a breaking bug tho, just some little inconvenient bug.

Will take a look at this later<sup>tm</sup> if I have time but putting it here in case you're interested.

**Comment by crash5band** [comment]
Fixed as of #7
