### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RaiuKJ77** [crash5band/MikuMikuWorld#61]
How to set a preview point (part of the song when you select your song on Sonolus)?
I know, this isn't issue but couldn't find any information about setting preview point. I'll apologize for it.

**Comment by crash5band** [comment]
I think it's up to the server to implement that. Most likely when submitting your chart. The chart files do not contain this data

**Comment by RaiuKJ77** [comment]
> I think it's up to the server to implement that. Most likely when submitting your chart. The chart files do not contain this data

Ah I see. Ty for the reply.
