### ISSUE TITLE
Sideway Flick Judgement Issue

### ISSUE THREAD

**Issue by RaiuKJ77** [crash5band/MikuMikuWorld#63]
When I play my own chart, the sideway flick notes still gives ‘perfect’ judgement even I swiped opposite side which causes ‘great’ in original. (Around 0~1 second and 5~6 second) Is it an error or can be fixed?

https://github.com/crash5band/MikuMikuWorld/assets/171953529/c394b640-c1be-4991-b322-286ae1c3bc48

**Comment by crash5band** [comment]
Sonolus issue
