### ISSUE TITLE
Question: Will there be a macOS version?

### ISSUE THREAD

**Issue by UriBaruch** [crash5band/MikuMikuWorld#66]
I don't own a computer with windows, so i just wondered if there will be a macOS version anytime soon (I know there are other solutions in browser, but there are some features that are missing there, like trace notes and speed adjustments)

**Comment by crash5band** [comment]
No plans for a mac version but you can use wine (there is a guide in the wiki). Be careful tho because GLFW is broken on mac and vsync does not work.
