### ISSUE TITLE
Bug: The output sus file does not have a line break

### ISSUE THREAD

**Issue by Kyonkrnk** [crash5band/MikuMikuWorld#71]
It seems that when exporting a sus file in MMW3.2.4, the line breaks are removed.
![スクリーンショット 2024-11-22 231512](https://github.com/user-attachments/assets/ca0a4b67-1cc1-4e79-a172-7b2fc6024a87)

**Comment by crash5band** [comment]
Fixed with e7bbc03

Apologies.
I'll create a new release soon
