### ISSUE TITLE
All tabs are separated on local build

### ISSUE THREAD

**Issue by sevenc-nanashi** [crash5band/MikuMikuWorld#8]
![image](https://user-images.githubusercontent.com/59691627/186882988-3b83ccb6-25c8-4cc0-bf2a-ff00cd3acaa4.png)
I tried to build MMW on my computer, but it's broken.
I'm using Visual Studio 2022, `glfw-3.3.8.bin.WIN64`.

**Comment by crash5band** [comment]
Fixed with the latest commit 116bfa37dd7fccb14c7545ecd3e71fb34ffbfc5e
